# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/hlteusc/setup-makefiles.sh

PRODUCT_COPY_FILES += \
	 vendor/samsung/hlteusc/proprietary/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \
        vendor/samsung/hlteusc/proprietary/vendor/firmware/libpn547_fw_pku.so:system/vendor/firmware/libpn547_fw_pku.so \
        vendor/samsung/hlteusc/proprietary/vendor/firmware/libpn547_fw_platform.so:system/vendor/firmware/libpn547_fw_platform.so \
	vendor/samsung/hlteusc/proprietary/vendor/firmware/BT_FW_VER_BCM4339_003.001.009.0031.0131_ORC_H-USCC.hcd:system/vendor/firmware/BT_FW_VER_BCM4339_003.001.009.0031.0131_ORC_H-USCC.hcd \
        vendor/samsung/hlteusc/proprietary/lib/libsensirion_h_7.so:system/lib/libsensirion_h_4.so \
        vendor/samsung/hlteusc/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
        vendor/samsung/hlteusc/proprietary/lib/libril.so:system/lib/libril.so \
	vendor/samsung/hlteusc/proprietary/lib/libnfc.so \
	vendor/samsung/hlteusc/proprietary/lib/libnfc_jni.so \
	vendor/samsung/hlteusc/proprietary/lib/libnfc_log.so \
	vendor/samsung/hlteusc/proprietary/lib/libnfc_ndef.so \
        vendor/samsung/hlteusc/proprietary/lib/hw/nfc.MSM8974.so:system/lib/hw/nfc.MSM8974.so \
        vendor/samsung/hlteusc/proprietary/lib/hw/sensors.msm8974.so:system/lib/hw/sensors.msm8974.so
